import { Order, Product } from './types';

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    userId: 'demo',
    name: 'Classic Casual Denim Shirt',
    sku: 'DSH-X01',
    price: 1200,
    sizeOptions: ['S', 'M', 'L', 'XL'],
    colorOptions: ['Blue Ocean', 'Dark Indigo', 'Charcoal Grey'],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prod-2',
    userId: 'demo',
    name: 'Premium Leather Chino Belt',
    sku: 'LBT-P55',
    price: 850,
    sizeOptions: ['32', '34', '36', '38'],
    colorOptions: ['Camel Brown', 'Rustic Black', 'Chestnut'],
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prod-3',
    userId: 'demo',
    name: 'Smart Stretch Slim Fit Polo',
    sku: 'POL-S32',
    price: 750,
    sizeOptions: ['M', 'L', 'XL', 'XXL'],
    colorOptions: ['Ruby Red', 'Slate Grey', 'Classic White', 'Jet Black'],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const DEMO_ORDERS: Order[] = [
  {
    id: 'NOA1B2C3D4',
    userId: 'demo',
    customerName: 'Anik Rahman',
    customerPhone: '01712345678',
    deliveryAddress: 'House 42, Road 11, Banani, Dhaka 1213',
    productName: 'Classic Casual Denim Shirt',
    quantity: 2,
    size: 'L',
    color: 'Dark Indigo',
    price: 2400,
    deliveryCharge: 80,
    status: 'pending',
    notes: 'Please call before delivery. Avoid noon timings.',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'NOK5J8D2P9',
    userId: 'demo',
    customerName: 'Nusrat Jahan',
    customerPhone: '01998765432',
    deliveryAddress: 'Flat 3B, Sector 4, Uttara, Dhaka 1230',
    productName: 'Smart Stretch Slim Fit Polo',
    quantity: 1,
    size: 'M',
    color: 'Ruby Red',
    price: 750,
    deliveryCharge: 80,
    status: 'processing',
    notes: 'Gift pack request. Please include a greetings note.',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'NOS7T3V1M8',
    userId: 'demo',
    customerName: 'Tanvir Hossain Malik',
    customerPhone: '01822446688',
    deliveryAddress: 'Holding 88, VIP Road, GEC Circle, Chittagong',
    productName: 'Premium Leather Chino Belt',
    quantity: 1,
    size: '34',
    color: 'Camel Brown',
    price: 850,
    deliveryCharge: 150,
    status: 'shipped',
    notes: 'Shipped via Pathao courier services.',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'NOW9Q2E7R4',
    userId: 'demo',
    customerName: 'Srabonti Datta',
    customerPhone: '01555667788',
    deliveryAddress: 'Zilla School Road, Sadar, Sylhet 3100',
    productName: 'Classic Casual Denim Shirt',
    quantity: 1,
    size: 'S',
    color: 'Blue Ocean',
    price: 1200,
    deliveryCharge: 150,
    status: 'delivered',
    notes: 'Fulfillment completed and payment received.',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'NOZ4X6C8V1',
    userId: 'demo',
    customerName: 'Jamil Hasan Karim',
    customerPhone: '01611112233',
    deliveryAddress: 'Mymensingh Lane, Sherpur Town, Mymensingh',
    productName: 'Smart Stretch Slim Fit Polo',
    quantity: 3,
    size: 'XL',
    color: 'Classic White',
    price: 2250,
    deliveryCharge: 150,
    status: 'cancelled',
    notes: 'Customer changed delivery location out of service bounds.',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  }
];
